[package]
name = "dfi18n"
edition = "2024"

[lib]
name = "dfi18n"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
cp437_string = { workspace = true }
cpp = { workspace = true }
executable = { workspace = true }
rule_based_translator = { workspace = true }

lua53-sys = { workspace = true }
sdl2-sys = { workspace = true }

macros = { workspace = true }

anyhow = { workspace = true }
backtrace = { workspace = true }
base16ct = { workspace = true }
csv = { workspace = true }
flexi_logger = { workspace = true }
fontdue = { workspace = true }
indexmap = { workspace = true }
libloading = { workspace = true }
log = { workspace = true }
regex = { workspace = true }
retour = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true }
ureq = { version = "3", features = ["json"] }
serde_json = "1"
parking_lot = "0.12"
with_builtin_macros = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { workspace = true }
